name: Build and Deploy to DigitalOcean BLOG Droplet

on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Transfer dist folder to droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.BLOG_DO_DROPLET_HOST}}
          username: ${{ secrets.BLOG_DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.BLOG_DO_PORT }}
          source: 'dist/spa'
          target: '/var/www/blog'
          strip_components: 1
